# iNeuron_Assignment7 (Numpy)

In [ ]:
#Write a function so that the columns of the output matrix are powers of the input vector.
#The order of the powers is determined by the increasing boolean argument. Specifically, when
#increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

#HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [1]:
import numpy as np
input_vector = np.array([1,2,3,4,5])
n = 5
input_vector

array([1, 2, 3, 4, 5])

In [2]:
def matrixGeoProgression(input_vector,n,increasing):
    if increasing:
        output = np.matrix([x**i for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    else:
        output = np.matrix([x**(n-i-1) for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    return output

In [3]:
matrix_inc=matrixGeoProgression(input_vector,n,True)
matrix_inc

matrix([[  1,   1,   1,   1,   1],
        [  1,   2,   4,   8,  16],
        [  1,   3,   9,  27,  81],
        [  1,   4,  16,  64, 256],
        [  1,   5,  25, 125, 625]])

In [4]:
matrix_dec=matrixGeoProgression(input_vector,n,False)
matrix_dec

matrix([[  1,   1,   1,   1,   1],
        [ 16,   8,   4,   2,   1],
        [ 81,  27,   9,   3,   1],
        [256,  64,  16,   4,   1],
        [625, 125,  25,   5,   1]])

In [ ]:
# Problem Statement 2:
# Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
# The moving average sequence has n-k+1 elements as shown below.
# The moving averages with k=4 of a ten-value sequence (n=10) is shown below
# i 1 2 3 4 5 6 7 8 9 10
# ===== == == == == == == == == == ==
# Input 10 20 30 40 50 60 70 80 90 100
# y1 25 = (10+20+30+40)/4
# y2 35 = (20+30+40+50)/4
# y3 45 = (30+40+50+60)/4
# y4 55 = (40+50+60+70)/4
# y5 65 = (50+60+70+80)/4
# y6 75 = (60+70+80+90)/4
# y7 85 = (70+80+90+100)/4
# Thus, the moving average sequence has n-k+1=10-4+1=7 values.
# Question: Write a function to find moving average in an array over a window:
# Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [35]:
def movingAvg(input_values, k):
    for i in range(input_values.size-(k-1)):
        output=0
        j=0
        for j in range(k):   
            output += input_values[i]
            i=i+1
        output=output/k
        print("y"+str(i-(k-1))+" = "+str(output))

In [36]:
input_values = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = 3
n = input_values.size - k + 1
print("Number of values in the moving average sequence : " + str(n))
movingAvg(input_values,k)

Number of values in the moving average sequence : 11
y1 = 5.0
y2 = 4.666666666666667
y3 = 5.666666666666667
y4 = 6.666666666666667
y5 = 9.666666666666666
y6 = 28.666666666666668
y7 = 49.333333333333336
y8 = 72.66666666666667
y9 = 84.0
y10 = 93.33333333333333
y11 = 116.33333333333333
